config/routes.rb
Rails.application.routes.draw do
  
  root 'tasks#index'

  namespace :admin do
    resources :users
  end
  resources :users
  resources :tasks
  resources :sessions , only:[:new ,  :create , :destroy]
  resources :groups
  resources :group_members, only:[:create, :destroy]
  resources :labels , only:[:index]
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_members, dependent: :destroy
  has_many :assign_members , through: :group_members , source: :user


  def assign_member(user)
    group_members.create(user: user)
  end

  def owner?(user)
    return false if user.nil?
    self.user_id == user.id
  end

  def assign?(user)
    return false if user.nil?
    return false unless self.group_members.present?
    # return self.assign_members.any?{ |assign_member| assign_member.id == user.id }
    return assign_members.exists?(id: user.id)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group , only:[:edit, :update, :destroy, :show]

  def index
    @groups = Group.all
  end
  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    redirect_to groups_path unless owner?

    if @group.save
      @group.assign_member(current_user)
      flash[:success] = t('msg.new_group_complete')
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    redirect_to groups_path unless owner?
  end

  def update
    redirect_to groups_path unless owner?
    @group.update(group_params)
    redirect_to groups_path , notice: "グループ「#{@group.name}」を更新しました。"
  end

  def show
    redirect_to groups_path unless assign_group?
  end

  def destroy
    redirect_to groups_path unless owner?
    @group.destroy
    redirect_to groups_path , notice: "グループ「#{@group.name}」を削除しました。"
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def owner?
    return true if @group.owner?(current_user)
    flash[:danger] =  '処理をする権限がありません'
    false
  end

  def assign_group?
    return true if @group.assign?(current_user)
    flash[:danger] =  '参照する権限がありません'
    false
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: @group , local: true , class:"form_container" ) do |f| %>

  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name,class:"form-control"%>
  </div>

  <div class="align_center">
    <%= f.submit t('btn.submit') ,class:"btn-sm"%>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="width_50">
  <h1><%= t('view.edit_group_title') %></h1>

  <%= render 'form' %>
</div>

app/views/groups/index.html.erb
<div class="width_80">
  <h1><%= t('view.group_title') %></h1>

  <%= link_to t('btn.new') , new_group_path ,class: "btn-sm btn-dark"%>
  <table class="index_container">
    <th class="width_20"><%= Group.human_attribute_name('name')%></th>
    <th class="width_30"></th>
    <% @groups.each do |group| %>
      <tr>
        <td class="width_20"><%= group.name %></td>
        <td class="width_30">
        <% if group.assign?(current_user) %>
          <%= link_to t('btn.show'), group_path(group.id),class:"btn-sm btn-secondary"%>
          <%= link_to '脱退',  group_member_path(id: group.id, user_id: current_user.id) , method: :delete , data:{confirm: "脱退してもよろしいですか？"}, class:"btn-sm btn-danger" %>
        <% else %>
          <%= link_to '参加', group_members_path(group_id: group.id),  method: :post, class:"btn-sm btn-primary"%>
        <% end %>

        <% if group.owner?(current_user)%>  
          <%= link_to t('btn.update') , edit_group_path(group.id) ,class:"btn-sm btn-primary"%>
          <%= link_to t('btn.destroy'), group_path(group.id), method: :delete, data:{ confirm: t('msg.confirm_destroy')}, class:"btn-sm btn-danger"%>
        <% end %>
        </td>
      </tr>
    <% end %>

  </table>
</div>

app/views/groups/new.html.erb
<div class="width_50">
  <h1><%= t('view.new_group_title') %></h1>

  <%= render 'form' %>
</div>

app/views/groups/show.html.erb
<div class="width_50">
  <h1><%= t('view.show_group_title') %></h1>

  <div class="d-flex align-items-center mt-4 mb-4">
      <div class="ml-auto posts_button">
      </div>
  </div>

  <div class="card index_container">
    <div class="card-header .bg-dark">
      <h4><%= @group.name %></h4>
    </div>
    <div class="card-body">
      <p class="card-text">メンバー一覧</p>
      <% @group.assign_members.each do |member| %>
        <p>
          名前：<%= member.name%>
          <% if @group.owner?(current_user) or member.id == current_user.id %>  
            <%= link_to '削除' , group_member_path(user_id: member.id) , method: :delete , data:{confirm: "解除してもよろしいですか？"}, class:"btn-xs btn-danger" %>
          <% end %>
        </p>
        <% if member.tasks.present? %>
          <table class="index_container">
            <th class="width_20"><%= Task.human_attribute_name('title')%></th>
            <th class="width_30"></th>
            <th class="width_10"></th>
            <% member.tasks.each do |task|%>
              <tr>
                <td class="width_20"><%= task.title%></td>
                <td class="width_30"><%= link_to t('btn.show'), task_path(task.id),class:"btn-xs btn-secondary"%></td>
                <td class="width_10"><%= task.find_read_task(current_user)? '既読' : '未読'%></td>
              </tr>
            <% end %>
          </table>
        <% end %>
      <% end %> 
    </div>
    <div class="card-footer align_center">
      <%= link_to t('btn.to_index') , groups_path ,class:"btn-sm btn-dark"%>
    </div>
  </div>

</div>