config/routes.rb
Rails.application.routes.draw do
  
  root 'tasks#index'

  namespace :admin do
    resources :users
  end
  resources :users
  resources :tasks
  resources :sessions , only:[:new ,  :create , :destroy]
  resources :groups
  resources :group_members, only:[:create, :destroy]
  resources :labels , only:[:index]
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name , presence: true , length: {maximum:20}
  validates :mail , presence: true , format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  before_validation{:mail.downcase}
  has_secure_password
  validates :password , presence: true , length: {minimum:6}
  has_many :tasks , dependent: :destroy
  enum role: { 管理者:true, 一般:false}
  has_many :groups
  has_many :group_members, dependent: :destroy
  has_many :assign_groups , through: :group_members , source: :group
  has_many :read_tasks ,dependent: :destroy
  has_one_attached :icon

  def self.current_user=(user)
    Thread.current[:current_user] = user
  end

  def self.current_user
    Thread.current[:current_user]
  end

  def user_is_yourself?(user)
    return false if user.nil?
    self.id == user.id
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :set_user , only:[:edit , :update ,:show ,:destroy]
  before_action :admin_user?
  before_action :delete_admin_user? , only:[:update ,:destroy]

  def index
    @users = User.all.includes(:tasks)
  end

  def new
    if params[:back]
      @user = User.new(user_params)
    else
      @user = User.new
    end
  end

  def create
    @user =  User.new(user_params)
    if @user.save
      flash[:success] = t('msg.user_create_complete')
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    # if  delete_admin_user?
      if @user.update(user_params)
        flash[:success] = t('msg.user_update_complete')
        redirect_to admin_users_path
      else
        render 'edit'
      end
    # else
    #   render 'edit'
    # end
  end

  def destroy
    @user.destroy
    flash[:danger] = t('msg.user_destroy_complete')
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name , :mail , :password , :password_confirmation ,:role)
  end

  def admin_user?
    raise Forbidden if current_user.role == User.human_attribute_name('role_common')
  end

  def delete_admin_user?
    admin_user_count = User.where(role: true).count

    return if admin_user_count > 1

    if action_name == 'destroy'
      redirect_back(fallback_location: request.url)
      flash[:danger] = t('err_msg.confirm_admin')
      return
    end

    if user_params[:role] == User.human_attribute_name('role_common')
      redirect_back(fallback_location: request.url)
      flash[:danger] = t('err_msg.confirm_admin')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :set_user , only:[:show]
  def new
    redirect_to tasks_path if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = t('msg.user_create_complete')
      session[:user_id] = @user.id
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  def show
    begin
      raise 'Something went wrong!'
    rescue => exception
      Bugsnag.notify(exception)
    end
    check_another_user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name , :mail , :password , :password_confirmation, :icon)
  end

  def check_another_user
    unless @user.user_is_yourself?(current_user)
      flash[:success] = t('msg.confirm_another_user')
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def admin_new_or_edit
    if action_name == "new"  or action_name == "create" 
      admin_users_path
    elsif action_name == "edit" or action_name == "update" 
      admin_user_path
    end
  end
end

app/views/admin/users/_form.html.erb
<% if @user.errors.any? %>
<div id="error_explantion">
  <h2><%= pluralize(@user.errors.count ,  t('err_msg.err_count') )%><%= t('err_msg.has_error') %></h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li><br>
    <% end %>
  </ul>
  </div>
<% end %>
<%= form_with(model: @user , local: true , class:"form_container" ,url: admin_new_or_edit) do |f| %>

  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name,class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :mail%>
    <%= f.email_field :mail,class:"form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :password%>
    <%= f.password_field :password,class:"form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation%>
    <%= f.password_field :password_confirmation,class:"form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :role%>
    <%= f.select :role,  User.roles.keys ,class:"form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :icon%>
    <%= f.file_field :icon, class:"form-control"%>
  </div>

  <div class="align_center">
    <%= f.submit t('btn.submit') ,class:"btn-sm"%>
    <%= link_to t('btn.to_index') , admin_users_path ,class:"btn-sm btn-dark"%>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="width_50">
  <h1><%= t('view.edit_user_title') %></h1>

  <%= render 'form'%>
</div>

app/views/admin/users/index.html.erb
<div class="width_80">
  <h1><%= t('view.admin_title') %></h1>

  <%= link_to t('btn.new') , new_admin_user_path ,class: "btn-sm btn-dark"%>
  <table class="index_container">
    <th class="width_20"><%= User.human_attribute_name('name')%></th>
    <th class="width_20"><%= User.human_attribute_name('mail')%></th>
    <th class="width_20"><%= Task.human_attribute_name('count')%></th>
    <th class="width_20"><%= User.human_attribute_name('role')%></th>
    <th class="width_10"></th>
    <% @users.each do |user| %>
      <tr>
        <td class="width_20"><%= user.name %></td>
        <td class="width_20"><%= user.mail %></td>
        <td class="width_20"><%= user.tasks.size %></td>
        <td class="width_20"><%= user.role %></td>
        <td class="width_10">               
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              ■
            </a>
            <div class="dropdown-menu mr-auto width_200" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to t('btn.show'), admin_user_path(user.id),class:"btn-sm btn-secondary margin_left5"%>
              <%= link_to t('btn.update') , edit_admin_user_path(user.id) ,class:"btn-sm btn-primary margin_left5"%>
              <%= link_to t('btn.destroy'), admin_user_path(user.id), method: :delete, data:{ confirm: t('msg.confirm_destroy')} ,class:"btn-sm btn-danger margin_left5"%>
            </div>
          </li>
        </td>
      </tr>
    <% end %>

  </table>
</div>

app/views/admin/users/new.html.erb
<div class="width_50">
  <h1><%= t('view.new_user_title') %></h1>

  <%= render 'form' %>
</div>

app/views/admin/users/show.html.erb
<div class="width_50">
  <h1><%= t('view.show_user_title') %></h1>

  <div class="d-flex align-items-center mt-4 mb-4">
      <div class="ml-auto posts_button">
      </div>
  </div>

  <div class="card">
    <div class="card-header .bg-dark">
      <h4><%= @user.name %></h4>
      <%= User.human_attribute_name('icon')%>:
      <%= image_tag @user.icon.variant(resize:'100x100') if @user.icon.attached?%><br>
    </div>
    <div class="card-body height_200">
        <p class="card-text"><%= User.human_attribute_name('mail')%>:<%= @user.mail%></p>
    </div>
    <div class="card-footer align_center">
      <%= link_to t('btn.to_index') , admin_users_path ,class:"btn-sm btn-dark"%>
    </div>
  </div>

</div>