config/routes.rb
Rails.application.routes.draw do
  
  root 'tasks#index'

  namespace :admin do
    resources :users
  end
  resources :users
  resources :tasks
  resources :sessions , only:[:new ,  :create , :destroy]
  resources :groups
  resources :group_members, only:[:create, :destroy]
  resources :labels , only:[:index]
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>
    <header>
      <div class="header-left">
        <h1><%=t('view.page_title')%></h1>
        <h1>オプション１０</h1>
      </div>
      <div class="header-right">
        <% if logged_in? %>
          <li><%= link_to t('btn.label') , labels_path ,class:"btn btn-dark btn-lg"%></li>
          <li><%= link_to t('btn.mygroup') , groups_path ,class:"btn btn-dark btn-lg"%></li>
          <li><%= link_to t('btn.mypage') , user_path(current_user.id) ,class:"btn btn-dark btn-lg"%></li>
          <li><%= link_to t('btn.logout') , session_path(current_user.id) ,
          method: :delete ,data:{confirm:t('msg.confirm_logout')},class:"btn btn-danger btn-lg"%></li>
        <% else %>
          <li><%= link_to t('btn.login') , new_session_path ,class:"btn btn-dark btn-lg"%></li>
          <li><%= link_to t('btn.signin') , new_user_path ,class:"btn btn-primary btn-lg"%></li>
        <% end %>    
      <p></p>
      </div>
    </header>

  <body>
    <div class="container">
      <%= render partial: 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    <footer>
      <p><%=t('view.footer_title')%></p>
    </footer>
  </body>
</html>